// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistence.Data.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.AlumnoMatriculaAsignatura", b =>
                {
                    b.Property<int>("IdCursoEscolarFk")
                        .HasColumnType("int");

                    b.Property<int>("IdAlumnoFk")
                        .HasColumnType("int");

                    b.Property<int>("IdAsignaturaFk")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("IdCursoEscolarFk", "IdAlumnoFk", "IdAsignaturaFk");

                    b.HasIndex("IdAlumnoFk");

                    b.HasIndex("IdAsignaturaFk");

                    b.ToTable("alumnoMatriculaAsignatura", (string)null);

                    b.HasData(
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 1,
                            IdAsignaturaFk = 1,
                            Id = 1
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 1,
                            IdAsignaturaFk = 2,
                            Id = 2
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 1,
                            IdAsignaturaFk = 3,
                            Id = 3
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 2,
                            IdAsignaturaFk = 1,
                            Id = 4
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 2,
                            IdAsignaturaFk = 2,
                            Id = 5
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 2,
                            IdAsignaturaFk = 3,
                            Id = 6
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 4,
                            IdAsignaturaFk = 1,
                            Id = 7
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 4,
                            IdAsignaturaFk = 2,
                            Id = 8
                        },
                        new
                        {
                            IdCursoEscolarFk = 1,
                            IdAlumnoFk = 4,
                            IdAsignaturaFk = 3,
                            Id = 9
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 1,
                            Id = 10
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 2,
                            Id = 11
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 3,
                            Id = 12
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 4,
                            Id = 13
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 5,
                            Id = 14
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 6,
                            Id = 15
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 7,
                            Id = 16
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 8,
                            Id = 17
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 9,
                            Id = 18
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 24,
                            IdAsignaturaFk = 10,
                            Id = 19
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 1,
                            Id = 20
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 2,
                            Id = 21
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 3,
                            Id = 22
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 4,
                            Id = 23
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 5,
                            Id = 24
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 6,
                            Id = 25
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 7,
                            Id = 26
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 8,
                            Id = 27
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 9,
                            Id = 28
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 23,
                            IdAsignaturaFk = 10,
                            Id = 29
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 1,
                            Id = 30
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 2,
                            Id = 31
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 3,
                            Id = 32
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 4,
                            Id = 33
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 5,
                            Id = 34
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 6,
                            Id = 35
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 7,
                            Id = 36
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 8,
                            Id = 37
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 9,
                            Id = 38
                        },
                        new
                        {
                            IdCursoEscolarFk = 5,
                            IdAlumnoFk = 19,
                            IdAsignaturaFk = 10,
                            Id = 39
                        });
                });

            modelBuilder.Entity("Domain.Entities.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Creditos")
                        .HasColumnType("float");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<int>("Curso")
                        .HasColumnType("int");

                    b.Property<int>("IdGradoFk")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfesorFk")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoAsignaturaFk")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdGradoFk");

                    b.HasIndex("IdProfesorFk");

                    b.HasIndex("IdTipoAsignaturaFk");

                    b.ToTable("asignatura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Algegra lineal y matematica discreta"
                        },
                        new
                        {
                            Id = 2,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Calculo"
                        },
                        new
                        {
                            Id = 3,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Fisica para informatica"
                        },
                        new
                        {
                            Id = 4,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Introduccion a la programacion"
                        },
                        new
                        {
                            Id = 5,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Organizacion y gestion de empresas"
                        },
                        new
                        {
                            Id = 6,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Estadistica"
                        },
                        new
                        {
                            Id = 7,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Estructura y tecnologia de computadores"
                        },
                        new
                        {
                            Id = 8,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Fundamentos de electronica"
                        },
                        new
                        {
                            Id = 9,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Logica y algoritmica"
                        },
                        new
                        {
                            Id = 10,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Metodologia de la programacion"
                        },
                        new
                        {
                            Id = 11,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Arquitectura de Computadores"
                        },
                        new
                        {
                            Id = 12,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Estructura de Datos y Algoritmos I"
                        },
                        new
                        {
                            Id = 13,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Ingenieria del Software"
                        },
                        new
                        {
                            Id = 14,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Sistemas Inteligentes"
                        },
                        new
                        {
                            Id = 15,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Sistemas Operativos"
                        },
                        new
                        {
                            Id = 16,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 17,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Estructura de Datos y Algoritmos II"
                        },
                        new
                        {
                            Id = 18,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Fundamentos de Redes de Computadores"
                        },
                        new
                        {
                            Id = 19,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 4,
                            IdProfesorFk = 3,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Planificaciin y Gestiin de Proyectos Informaticos"
                        },
                        new
                        {
                            Id = 20,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Programacion de Servicios Software"
                        },
                        new
                        {
                            Id = 21,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdProfesorFk = 14,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Desarrollo de interfaces de usuario"
                        },
                        new
                        {
                            Id = 22,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Ingenieria de Requisitos"
                        },
                        new
                        {
                            Id = 23,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Integracion de las Tecnologías de la Informacion en las Organizaciones"
                        },
                        new
                        {
                            Id = 24,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Modelado y Diseño del Software 1"
                        },
                        new
                        {
                            Id = 25,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Multiprocesadores"
                        },
                        new
                        {
                            Id = 26,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Seguridad y cumplimiento normativo"
                        },
                        new
                        {
                            Id = 27,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Sistema de Información para las Organizaciones"
                        },
                        new
                        {
                            Id = 28,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Tecnologias web"
                        },
                        new
                        {
                            Id = 29,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Teoria de codigos y criptografia"
                        },
                        new
                        {
                            Id = 30,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Administracion de bases de datos"
                        },
                        new
                        {
                            Id = 31,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Herramientas y Metodos de Ingeniería del Software"
                        },
                        new
                        {
                            Id = 32,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Informatica industrial y robotica"
                        },
                        new
                        {
                            Id = 33,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Ingenieria de Sistemas de Informacion"
                        },
                        new
                        {
                            Id = 34,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Modelado y Diseño del Software 2"
                        },
                        new
                        {
                            Id = 35,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Negocio Electronico"
                        },
                        new
                        {
                            Id = 36,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Perifericos e interfaces"
                        },
                        new
                        {
                            Id = 37,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Sistemas de tiempo real"
                        },
                        new
                        {
                            Id = 38,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Tecnologias de acceso a red"
                        },
                        new
                        {
                            Id = 39,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Tratamiento digital de imagenes"
                        },
                        new
                        {
                            Id = 40,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Administracion de redes y sistemas operativos"
                        },
                        new
                        {
                            Id = 41,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Almacenes de Datos"
                        },
                        new
                        {
                            Id = 42,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Fiabilidad y Gestión de Riesgos"
                        },
                        new
                        {
                            Id = 43,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Lineas de Productos Software"
                        },
                        new
                        {
                            Id = 44,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Procesos de Ingenieria del Software 1"
                        },
                        new
                        {
                            Id = 45,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Tecnologias multimedia"
                        },
                        new
                        {
                            Id = 46,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Analisis y planificación de las TI"
                        },
                        new
                        {
                            Id = 47,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Desarrollo Rapido de Aplicaciones"
                        },
                        new
                        {
                            Id = 48,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Gestion de la Calidad y de la Innovacion Tecnologica"
                        },
                        new
                        {
                            Id = 49,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Inteligencia del Negocio"
                        },
                        new
                        {
                            Id = 50,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Procesos de Ingenieria del Software 2"
                        },
                        new
                        {
                            Id = 51,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 4,
                            IdGradoFk = 4,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Seguridad Informatica"
                        },
                        new
                        {
                            Id = 52,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Biologia celular"
                        },
                        new
                        {
                            Id = 53,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Fisica"
                        },
                        new
                        {
                            Id = 54,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Matematicas I"
                        },
                        new
                        {
                            Id = 55,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Quimica general"
                        },
                        new
                        {
                            Id = 56,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Quimica organica"
                        },
                        new
                        {
                            Id = 57,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Biologia vegetal y animal"
                        },
                        new
                        {
                            Id = 58,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Bioquimica"
                        },
                        new
                        {
                            Id = 59,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Genetica"
                        },
                        new
                        {
                            Id = 60,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Matematicas II"
                        },
                        new
                        {
                            Id = 61,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 1,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 1,
                            Nombre = "Microbiologia"
                        },
                        new
                        {
                            Id = 62,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Botanica agricola"
                        },
                        new
                        {
                            Id = 63,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Fisiologia vegetal"
                        },
                        new
                        {
                            Id = 64,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Genetica molecular"
                        },
                        new
                        {
                            Id = 65,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Ingenieria bioquimica"
                        },
                        new
                        {
                            Id = 66,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Termodinamica y cinetica quimica aplicada"
                        },
                        new
                        {
                            Id = 67,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Biorreactores"
                        },
                        new
                        {
                            Id = 68,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Biotecnologia microbiana"
                        },
                        new
                        {
                            Id = 69,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Ingenieria genetica"
                        },
                        new
                        {
                            Id = 70,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Inmunologia"
                        },
                        new
                        {
                            Id = 71,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 2,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 2,
                            Nombre = "Virologia"
                        },
                        new
                        {
                            Id = 72,
                            Creditos = 4.5f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Bases moleculares del desarrollo vegetal"
                        },
                        new
                        {
                            Id = 73,
                            Creditos = 4.5f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Fisiologia animal"
                        },
                        new
                        {
                            Id = 74,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Metabolismo y biosintesis de biomoleculas"
                        },
                        new
                        {
                            Id = 75,
                            Creditos = 6f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Operaciones de separacion"
                        },
                        new
                        {
                            Id = 76,
                            Creditos = 4.5f,
                            Cuatrimestre = 1,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Patologia molecular de plantas"
                        },
                        new
                        {
                            Id = 78,
                            Creditos = 4.5f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Bioinformatica"
                        },
                        new
                        {
                            Id = 79,
                            Creditos = 4.5f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Biotecnologia de los productos hortofruticulas"
                        },
                        new
                        {
                            Id = 80,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Biotecnologia vegetal"
                        },
                        new
                        {
                            Id = 81,
                            Creditos = 4.5f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Genomica y proteomica"
                        },
                        new
                        {
                            Id = 82,
                            Creditos = 6f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Procesos biotecnologicos"
                        },
                        new
                        {
                            Id = 83,
                            Creditos = 4.5f,
                            Cuatrimestre = 2,
                            Curso = 3,
                            IdGradoFk = 7,
                            IdTipoAsignaturaFk = 3,
                            Nombre = "Técnicas instrumentales avanzadas"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CursoEscolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoFin")
                        .HasColumnType("int");

                    b.Property<int>("AnoInicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cursoEscolar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFin = 2014,
                            AnoInicio = 2015
                        },
                        new
                        {
                            Id = 2,
                            AnoFin = 2015,
                            AnoInicio = 2016
                        },
                        new
                        {
                            Id = 3,
                            AnoFin = 2016,
                            AnoInicio = 2017
                        },
                        new
                        {
                            Id = 4,
                            AnoFin = 2017,
                            AnoInicio = 2018
                        },
                        new
                        {
                            Id = 5,
                            AnoFin = 2018,
                            AnoInicio = 2019
                        });
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("departamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Informatica"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Matematicas"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Economia y Empresa"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Educacion"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Agronomia"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Quimica y Fisica"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Filologia"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Derecho"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Biologia y Geologia"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("grado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Grado en Ingeniería Agrícola (Plan 2015)"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Grado en Ingeniería Eléctrica (Plan 2014)"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Grado en Ingeniería Electrónica Industrial (Plan 2010)"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Grado en Ingeniería Informática (Plan 2015)"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Grado en Ingeniería Mecánica (Plan 2010)"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Grado en Ingeniería Química Industrial (Plan 2010)"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Grado en Biotecnología (Plan 2015)"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Grado en Ciencias Ambientales (Plan 2009)"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Grado en Matemáticas (Plan 2010)"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Grado en Química (Plan 2009)"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdSexoFk")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPersonaFk")
                        .HasColumnType("int");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdSexoFk");

                    b.HasIndex("IdTipoPersonaFk");

                    b.ToTable("persona", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ciudad = "Almeria",
                            Direccion = "C/ Real del barrio alto",
                            FechaNacimiento = new DateTime(1991, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "26902806M",
                            Nombre = "Salvador",
                            PrimerApellido = "Sanchez",
                            SegundoApellido = "Perez",
                            Telefono = "950254837"
                        },
                        new
                        {
                            Id = 2,
                            Ciudad = "Almería",
                            Direccion = "C/ Mercurio",
                            FechaNacimiento = new DateTime(1992, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "89542419S",
                            Nombre = "Juan",
                            PrimerApellido = "Saez",
                            SegundoApellido = "Vega",
                            Telefono = "618253876"
                        },
                        new
                        {
                            Id = 3,
                            Ciudad = "Almería",
                            Direccion = "C/ Marte",
                            FechaNacimiento = new DateTime(1979, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 2,
                            Nif = "11105554G",
                            Nombre = "Zoe",
                            PrimerApellido = "Ramirez",
                            SegundoApellido = "Gea",
                            Telefono = "618223876"
                        },
                        new
                        {
                            Id = 4,
                            Ciudad = "Almería",
                            Direccion = "C/ Estrella fugaz",
                            FechaNacimiento = new DateTime(2000, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "17105885A",
                            Nombre = "Pedro",
                            PrimerApellido = "Heller",
                            SegundoApellido = "Pagac"
                        },
                        new
                        {
                            Id = 5,
                            Ciudad = "Almería",
                            Direccion = "C/ Venus",
                            FechaNacimiento = new DateTime(1978, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "38223286T",
                            Nombre = "David",
                            PrimerApellido = "Schmidt",
                            SegundoApellido = "Fisher",
                            Telefono = "678516294"
                        },
                        new
                        {
                            Id = 6,
                            Ciudad = "Almería",
                            Direccion = "C/ Júpiter",
                            FechaNacimiento = new DateTime(1998, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "04233869Y",
                            Nombre = "José",
                            PrimerApellido = "Koss",
                            SegundoApellido = "Bayer",
                            Telefono = "628349590"
                        },
                        new
                        {
                            Id = 7,
                            Ciudad = "Almería",
                            Direccion = "C/ Neptuno",
                            FechaNacimiento = new DateTime(1999, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "97258166K",
                            Nombre = "Ismael",
                            PrimerApellido = "Strosin",
                            SegundoApellido = "Turcotte"
                        },
                        new
                        {
                            Id = 8,
                            Ciudad = "Almería",
                            Direccion = "C/ Saturno",
                            FechaNacimiento = new DateTime(1977, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 2,
                            Nif = "79503962T",
                            Nombre = "Cristina",
                            PrimerApellido = "Lemke",
                            SegundoApellido = "Rutherford",
                            Telefono = "669162534"
                        },
                        new
                        {
                            Id = 9,
                            Ciudad = "Almería",
                            Direccion = "C/ Urano",
                            FechaNacimiento = new DateTime(1996, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "82842571K",
                            Nombre = "Ramón",
                            PrimerApellido = "Herzog",
                            SegundoApellido = "Tremblay",
                            Telefono = "626351429"
                        },
                        new
                        {
                            Id = 10,
                            Ciudad = "Almería",
                            Direccion = "C/ Plutón",
                            FechaNacimiento = new DateTime(1977, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 2,
                            Nif = "61142000L",
                            Nombre = "Esther",
                            PrimerApellido = "Spencer",
                            SegundoApellido = "Lakin"
                        },
                        new
                        {
                            Id = 11,
                            Ciudad = "Almería",
                            Direccion = "C/ Andarax",
                            FechaNacimiento = new DateTime(1997, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "46900725E",
                            Nombre = "Daniel",
                            PrimerApellido = "Herman",
                            SegundoApellido = "Pacocha",
                            Telefono = "679837625"
                        },
                        new
                        {
                            Id = 12,
                            Ciudad = "Almería",
                            Direccion = "C/ Almanzora",
                            FechaNacimiento = new DateTime(1971, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 2,
                            Nif = "85366986W",
                            Nombre = "Carmen",
                            PrimerApellido = "Streich",
                            SegundoApellido = "Hirthe"
                        },
                        new
                        {
                            Id = 13,
                            Ciudad = "Almería",
                            Direccion = "C/ Guadalquivir",
                            FechaNacimiento = new DateTime(1980, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "73571384L",
                            Nombre = "Alfredo",
                            PrimerApellido = "Stiedemann",
                            SegundoApellido = "Morissette",
                            Telefono = "950896725"
                        },
                        new
                        {
                            Id = 14,
                            Ciudad = "Almería",
                            Direccion = "C/ Duero",
                            FechaNacimiento = new DateTime(1977, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "82937751G",
                            Nombre = "Manolo",
                            PrimerApellido = "Hamill",
                            SegundoApellido = "Kozey",
                            Telefono = "950263514"
                        },
                        new
                        {
                            Id = 15,
                            Ciudad = "Almería",
                            Direccion = "C/ Tajo",
                            FechaNacimiento = new DateTime(1980, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "80502866Z",
                            Nombre = "Alejandro",
                            PrimerApellido = "Kohler",
                            SegundoApellido = "Schoen",
                            Telefono = "668726354"
                        },
                        new
                        {
                            Id = 16,
                            Ciudad = "Almería",
                            Direccion = "C/ Sierra de los Filabres",
                            FechaNacimiento = new DateTime(1982, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "10485008K",
                            Nombre = "Antonio",
                            PrimerApellido = "Fahey",
                            SegundoApellido = "Considine"
                        },
                        new
                        {
                            Id = 17,
                            Ciudad = "Almería",
                            Direccion = "C/ Sierra de Gádor",
                            FechaNacimiento = new DateTime(1973, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "85869555K",
                            Nombre = "Guillermo",
                            PrimerApellido = "Ruecker",
                            SegundoApellido = "Upton"
                        },
                        new
                        {
                            Id = 18,
                            Ciudad = "Almería",
                            Direccion = "C/ Veleta",
                            FechaNacimiento = new DateTime(1976, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "04326833G",
                            Nombre = "Micaela",
                            PrimerApellido = "Monahan",
                            SegundoApellido = "Murray",
                            Telefono = "662765413"
                        },
                        new
                        {
                            Id = 19,
                            Ciudad = "Almería",
                            Direccion = "C/ Picos de Europa",
                            FechaNacimiento = new DateTime(1998, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 1,
                            Nif = "11578526G",
                            Nombre = "Inma",
                            PrimerApellido = "Lakin",
                            SegundoApellido = "Yundt",
                            Telefono = "678652431"
                        },
                        new
                        {
                            Id = 20,
                            Ciudad = "Almería",
                            Direccion = "C/ Quinto pino",
                            FechaNacimiento = new DateTime(1980, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 2,
                            Nif = "79221403L",
                            Nombre = "Francesca",
                            PrimerApellido = "Schowalter",
                            SegundoApellido = "Muller"
                        },
                        new
                        {
                            Id = 21,
                            Ciudad = "Almería",
                            Direccion = "C/ Los pinos",
                            FechaNacimiento = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "79089577Y",
                            Nombre = "Juan",
                            PrimerApellido = "Gutiérrez",
                            SegundoApellido = "López",
                            Telefono = "678652431"
                        },
                        new
                        {
                            Id = 22,
                            Ciudad = "Almería",
                            Direccion = "C/ Cabo de Gata",
                            FechaNacimiento = new DateTime(1999, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 1,
                            IdTipoPersonaFk = 1,
                            Nif = "41491230N",
                            Nombre = "Antonio",
                            PrimerApellido = "Domínguez",
                            SegundoApellido = "Guerrero",
                            Telefono = "626652498"
                        },
                        new
                        {
                            Id = 23,
                            Ciudad = "Almería",
                            Direccion = "C/ Zapillo",
                            FechaNacimiento = new DateTime(1996, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 1,
                            Nif = "64753215G",
                            Nombre = "Irene",
                            PrimerApellido = "Hernández",
                            SegundoApellido = "Martínez",
                            Telefono = "628452384"
                        },
                        new
                        {
                            Id = 24,
                            Ciudad = "Almería",
                            Direccion = "C/ Mercurio",
                            FechaNacimiento = new DateTime(1995, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdSexoFk = 2,
                            IdTipoPersonaFk = 1,
                            Nif = "85135690V",
                            Nombre = "Sonia",
                            PrimerApellido = "Gea",
                            SegundoApellido = "Ruiz",
                            Telefono = "678812017"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdDepartamentoFk")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonaFk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamentoFk");

                    b.HasIndex("IdPersonaFk");

                    b.ToTable("profesor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdDepartamentoFk = 1,
                            IdPersonaFk = 3
                        },
                        new
                        {
                            Id = 2,
                            IdDepartamentoFk = 2,
                            IdPersonaFk = 5
                        },
                        new
                        {
                            Id = 3,
                            IdDepartamentoFk = 3,
                            IdPersonaFk = 8
                        },
                        new
                        {
                            Id = 4,
                            IdDepartamentoFk = 4,
                            IdPersonaFk = 10
                        },
                        new
                        {
                            Id = 5,
                            IdDepartamentoFk = 4,
                            IdPersonaFk = 12
                        },
                        new
                        {
                            Id = 6,
                            IdDepartamentoFk = 6,
                            IdPersonaFk = 13
                        },
                        new
                        {
                            Id = 7,
                            IdDepartamentoFk = 1,
                            IdPersonaFk = 14
                        },
                        new
                        {
                            Id = 8,
                            IdDepartamentoFk = 2,
                            IdPersonaFk = 15
                        },
                        new
                        {
                            Id = 9,
                            IdDepartamentoFk = 3,
                            IdPersonaFk = 16
                        },
                        new
                        {
                            Id = 10,
                            IdDepartamentoFk = 4,
                            IdPersonaFk = 17
                        },
                        new
                        {
                            Id = 11,
                            IdDepartamentoFk = 5,
                            IdPersonaFk = 18
                        },
                        new
                        {
                            Id = 12,
                            IdDepartamentoFk = 6,
                            IdPersonaFk = 20
                        },
                        new
                        {
                            Id = 13,
                            IdDepartamentoFk = 2,
                            IdPersonaFk = 7
                        },
                        new
                        {
                            Id = 14,
                            IdDepartamentoFk = 3,
                            IdPersonaFk = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("sexo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "H"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "M"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoAsignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tipoAsignatura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Basica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Obligatoria"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Optativa"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tipoPersona", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Alumno"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Profesor"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AlumnoMatriculaAsignatura", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany("AlumnoMatriculaAsignaturas")
                        .HasForeignKey("IdAlumnoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("AlumnoMatriculaAsignaturas")
                        .HasForeignKey("IdAsignaturaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CursoEscolar", "CursoEscolar")
                        .WithMany("AlumnoMatriculaAsignaturas")
                        .HasForeignKey("IdCursoEscolarFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("CursoEscolar");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.Asignatura", b =>
                {
                    b.HasOne("Domain.Entities.Grado", "Grado")
                        .WithMany("Asignaturas")
                        .HasForeignKey("IdGradoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Profesor", "Profesor")
                        .WithMany("Asignaturas")
                        .HasForeignKey("IdProfesorFk");

                    b.HasOne("Domain.Entities.TipoAsignatura", "TipoAsignatura")
                        .WithMany("Asignaturas")
                        .HasForeignKey("IdTipoAsignaturaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grado");

                    b.Navigation("Profesor");

                    b.Navigation("TipoAsignatura");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.HasOne("Domain.Entities.Sexo", "Sexo")
                        .WithMany("Personas")
                        .HasForeignKey("IdSexoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoPersona", "TipoPersona")
                        .WithMany("Personas")
                        .HasForeignKey("IdTipoPersonaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sexo");

                    b.Navigation("TipoPersona");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.HasOne("Domain.Entities.Departamento", "Departamento")
                        .WithMany("Profesores")
                        .HasForeignKey("IdDepartamentoFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany("Profesores")
                        .HasForeignKey("IdPersonaFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.Asignatura", b =>
                {
                    b.Navigation("AlumnoMatriculaAsignaturas");
                });

            modelBuilder.Entity("Domain.Entities.CursoEscolar", b =>
                {
                    b.Navigation("AlumnoMatriculaAsignaturas");
                });

            modelBuilder.Entity("Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("Domain.Entities.Grado", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Navigation("AlumnoMatriculaAsignaturas");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Domain.Entities.Sexo", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Domain.Entities.TipoAsignatura", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Domain.Entities.TipoPersona", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
